### ISSUE TITLE
When accessing minio buckets, it is a good idea to provide the ability to skip SSL checks. Just add tls-insecure-skip-verify=true to the end of the https request

### ISSUE THREAD

**Issue by caesar168** [openimsdk/helm-charts#10]
### What would you like to share?

When accessing minio buckets, it is a good idea to provide the ability to skip SSL checks. Just add tls-insecure-skip-verify=true to the end of the https request

**Comment by cubxxw** [comment]
LinK https://github.com/openimsdk/helm-charts/issues/9
