### ISSUE TITLE
How to collect Openim logs with Loki in K8S for system health analysis.

### ISSUE THREAD

**Issue by caesar168** [openimsdk/helm-charts#11]
### What would you like to share?

How to collect Openim logs with Loki in K8S for system health analysis.

**Comment by cubxxw** [comment]
@caesar168 

I wanted to reach out to you and provide an update on our current progress regarding the management system and log collection. We are pleased to inform you that we will be utilizing the following technology stack: Loki, Promtail, Grafana, Prometheus, and Node Exporter.

To provide a brief explanation of each component, Loki is a horizontally-scalable, highly-available log aggregation system. Promtail is an agent which ships the logs from the application to Loki. Grafana is a platform for data visualization, monitoring, and analysis. Prometheus is a time-series database and monitoring system. Node Exporter is a Prometheus exporter for hardware and OS metrics.

We believe that this technology stack will allow us to efficiently manage and collect logs, as well as provide the necessary observability for our system. If you have any further questions or concerns, please do not hesitate to reach out to us.

**Comment by caesar168** [comment]
Very good! Regarding the log aggregation system, it should be assumed that a unified Loki system already exists for the user, so the project team only needs to provide an interface that allows the aggregation of Openim logs. The same is true for Grafana, where users basically have such a system and only need to provide an interface.
