### ISSUE TITLE
it is recommended that the project team can integrate the components appropriately,

### ISSUE THREAD

**Issue by caesar168** [openimsdk/helm-charts#15]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

When replicas are greater than 1, the following service pattern seems to be more appropriate, and it is recommended that the project team can integrate the components appropriately, and we are willing to cooperate with the testing:
openimserver-openim-0   11/11   running 
openimserver-openim-1   11/11   running

### Solution Description

and it is recommended that the project team can integrate the components appropriately。
openimserver-openim-0   11/11   running 
openimserver-openim-1   11/11   running
openimserver-openim-2   11/11   running
openimserver-openim-3   11/11   running
openimserver-openim-4   11/11   running

### Benefits

running component is clearer, and the O&M monitoring does not feel chaotic when there are multiple PODs

**Comment by cubxxw** [comment]
I understand your suggestion and will continue to optimize this part. Thank you for bringing this issue to my attention.

**Comment by skiffer-git** [comment]
Undergoing comprehensive testing, awaiting updates
