### ISSUE TITLE
how to use loki to collect logs in a k8s cluster? 

### ISSUE THREAD

**Issue by caesar168** [openimsdk/helm-charts#16]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

According to the instructions released in the official version, the 3.0 version or later regulates the logs, please consult an expert, how to use loki to collect logs in a k8s cluster? Does Openim provide an interface in K8S deployment?

### Solution Description

Does Openim provide an interface in K8S deployment?

### Benefits

It helps to analyze logs under the company's unified monitoring system

**Comment by cubxxw** [comment]
Dear @caesar168 
I wanted to inform you that I will be updating this repository in the next few days. Please keep an eye out for any differences. Thank you for your attention.

**Comment by skiffer-git** [comment]
Undergoing comprehensive testing, awaiting updates
