### ISSUE TITLE
It is recommended that the project team try to set the parameters of the components under K8S as quasi-standard as the standard configuration of the production environment

### ISSUE THREAD

**Issue by caesar168** [openimsdk/helm-charts#35]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

It is recommended that the project team try to set the parameters of the components under K8S as quasi-standard as the standard configuration of the production environment. For example, according to the average daily online 100,000, the throughput is 10 million, and the storage is 2T per day. This prevents the openim from looking like a toy. This approach is used in other large software, such as CEPH, which provides medium to high availability rather than minimal availability.

### Solution Description

For example, according to the average daily online 100,000, the throughput is 10 million, and the storage is 2T per day. This prevents the openim from looking like a toy. This approach is used in other large software, such as CEPH, which provides medium to high availability rather than minimal availability.

### Benefits

It can help users to provide the best parameters to the greatest extent.

**Comment by skiffer-git** [comment]
Undergoing comprehensive testing, awaiting updates
