### ISSUE TITLE
It is recommended that you install Prometheus and Grafana, loki and promtail automatically. 

### ISSUE THREAD

**Issue by caesar168** [openimsdk/helm-charts#36]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

components are all standard and open automatically by default, so users who don't need them can be disabled, instead of having them manually execute installation commands. This is also a common practice in many open source software today.

### Solution Description

components are all standard and open automatically by default, so users who don't need them can be disabled, instead of having them manually execute installation commands. This is also a common practice in many open source software today.

### Benefits

Minimize user operations.

**Comment by skiffer-git** [comment]
Undergoing comprehensive testing, awaiting updates
