### ISSUE TITLE
Is the chart image library sure to exist? Open https://openim.github.io/helm-charts browser returns an error code.

### ISSUE THREAD

**Issue by caesar168** [openimsdk/helm-charts#7]
### What would you like to share?

Is the chart image library sure to exist? Open https://openim.github.io/helm-charts browser returns an error code.helm repo add openim https://openim.github.io/helm-charts
Error: looks like "https://openim.github.io/helm-charts" is not a valid chart repository or cannot be reached: Get "https://openim.github.io/helm-charts/index.yaml": read tcp 192.168.10.10:8492->185.199.108.153:443: read: connection reset by peer

**Comment by caesar168** [comment]
excute：helm repo add openim https://openim.github.io/helm-charts
Error: looks like "https://openim.github.io/helm-charts" is not a valid chart repository or cannot be reached: Get "https://openim.github.io/helm-charts/index.yaml": read tcp 192.168.10.10:8492->185.199.108.153:443: read: connection reset by peer

**Comment by cubxxw** [comment]
You haven't set up the repository as a charts repository yet. Please clone this repository, navigate to the specified directory, and then use helm install to deploy. Make sure to read the README document.
